fn main() -> Result<(), failure::Error> {
    medea::run()
}
